/* THIS FILE IS GENERATED DO NOT EDIT */
#ifndef _EDITOR_AUTHORS_H
#define _EDITOR_AUTHORS_H
static const char *dev_founders[] = {
	"Juan Linietsky (reduz)",
	"Ariel Manzur (punto-)",
	0
};
static const char *dev_lead[] = {
	"Juan Linietsky (reduz)",
	0
};
static const char *dev_manager[] = {
	"R\303\251mi Verschelde (akien-mga)",
	0
};
static const char *dev_names[] = {
	"Alexander Holland (AlexHolly)",
	"Alexey Velikiy (jonyrock)",
	"Alket Rexhepi (alketii)",
	"Andreas Haas (Hinsbart)",
	"Anton Yabchinskiy (a12n)",
	"Aren Villanueva (kurikaesu)",
	"Ariel Manzur (punto-)",
	"Bastiaan Olij (BastiaanOlij)",
	"Bojidar Marinov (bojidar-bg)",
	"B\305\202a\305\274ej Szczygie\305\202 (zaps166)",
	"Carl Olsson (not-surt)",
	"Dana Olson (adolson)",
	"Daniel J. Ramirez (djrm)",
	"Emmanuel Leblond (touilleMan)",
	"Fabio Alessandrelli (Faless)",
	"Ferenc Arn (tagcup)",
	"Franklin Sobrinho (TheHX)",
	"Geequlim",
	"Gen (dbsGen)",
	"George Marques (vnen)",
	"Gerrit Gro\303\237kopf (Grosskopf)",
	"Gilles Roudiere (groud)",
	"Guilherme Felipe (guilhermefelipecgs)",
	"Hein-Pieter van Braam (hpvb)",
	"Hiroshi Ogawa (hi-ogawa)",
	"Hubert Jarosz (Marqin)",
	"Hugo Locurcio (Calinou)",
	"Ignacio Etcheverry (neikeq)",
	"Indah Sylvia (ISylvox)",
	"J08nY",
	"Jakub Grzesik (kubecz3k)",
	"Johan Manuel (29jm)",
	"Joshua Grams (JoshuaGrams)",
	"Juan Linietsky (reduz)",
	"Julian Murgia (StraToN)",
	"Kostadin Damyanov (Max-Might)",
	"L. Krause (eska014)",
	"Marc Gilleron (Zylann)",
	"Marcelo Fernandez (marcelofg55)",
	"Mariano Javier Suligoy (MarianoGnu)",
	"Mario Schlack (hurikhan)",
	"Masoud BH (masoudbh3)",
	"Nathan Warden (NathanWarden)",
	"Nuno Donato (nunodonato)",
	"Ovnuniarchos",
	"Patrick (firefly2442)",
	"Paul Batty (Paulb23)",
	"Pawel Kowal (pkowal1982)",
	"Pedro J. Est\303\251banez (RandomShaper)",
	"Poommetee Ketson (Noshyaar)",
	"Ralf H\303\266lzemer (rollenrolm)",
	"Ramesh Ravone (RameshRavone)",
	"Ray Koopa (RayKoopa)",
	"R\303\251mi Verschelde (akien-mga)",
	"Ruslan Mustakov (endragor)",
	"Saniko (sanikoyes)",
	"SaracenOne",
	"Theo Hallenius (TheoXD)",
	"Thomas Herzog (karroffel)",
	"Timo (toger5)",
	"V. Vamsi Krishna (vkbsb)",
	"Vinzenz Feenstra (vinzenz)",
	"Wilson E. Alvarez (Rubonnek)",
	"Zher Huei Lee (leezh)",
	"ZuBsPaCe",
	"\353\260\225\355\225\234\354\226\274 (volzhs)",
	"bruvzg",
	"est31",
	"marynate",
	"mrezai",
	"romulox-x",
	"yg2f (SuperUserNameMan)",
	0
};
#endif
