/* THIS FILE IS GENERATED DO NOT EDIT */
#ifndef _EDITOR_DONORS_H
#define _EDITOR_DONORS_H
static const char *donor_s_plat[] = {
	0
};
static const char *donor_s_gold[] = {
	"Gamblify <https://www.gamblify.com>",
	0
};
static const char *donor_s_mini[] = {
	"Andreas",
	"Andreas Hirschauer",
	"Christian Uldall Pedersen",
	"E Hewert",
	"Hein-Pieter van Braam",
	"Matthieu Huv\303\251",
	"Nathan Warden",
	"Neal Gompa (Conan Kudo)",
	"Olimpiu Metiu",
	"Ruslan Mustakov",
	"Slobodan Milnovic",
	0
};
static const char *donor_gold[] = {
	"Alexander Otto",
	"Asdf",
	"Blair Allen",
	"cheese65536",
	"Jake Bo",
	"Javier",
	"Manuele Finocchiaro",
	"Officine Pixel S.n.c.",
	"Ranoller",
	"R\303\251mi Verschelde",
	"Stephan Lanfermann",
	"Andreas Sch\303\274le",
	"Austen McRae",
	"Bernhard Liebl",
	"Gerald E Butler",
	"Jordan M Lucas",
	"Kris Michael",
	"BanjoNode2D",
	"Chris Serino",
	"Conrad Curry",
	"Craig Smith",
	"David Churchill",
	"Dean Harmon",
	"Guilherme Felipe de C. G. da Silva",
	"Henrique Alves",
	"Laurence Bannister",
	"Leo",
	"mhilbrunner",
	"Przemys\305\202aw Go\305\202\304\205b (n-pigeon)",
	"Robert Willes",
	"Robin Arys",
	"ScottMakesGames",
	"summerblind",
	"Testus Maximus",
	"Thomas Bjarnel\303\266f",
	"Xavier Tan",
	"Amanda Haldy",
	"Andreas Haas",
	"Bryanna M",
	"Chris Brown",
	"Cody Parker",
	"D",
	"Ezra Theunissen",
	"flesk",
	"Fran\303\247ois Cantin",
	"Hendrik Mans",
	"Jeppe Zapp",
	"Justin Arnold",
	"Justo Delgado Baud\303\255",
	"Leandro Voltolino",
	"Lucien Boudy",
	"Myles",
	"Noah",
	"Trent McPheron",
	"x1212",
	0
};
static const char *donor_silver[] = {
	"1D_Inc",
	"Alessandro Senese",
	"Alex Barsukov",
	"Anthony Bongiovanni",
	"Avencherus",
	"Bastian B\303\266hm",
	"Ben Vercammen",
	"Bryan Stevenson",
	"Christian Baune",
	"Christian Winter",
	"Collin Shooltz",
	"Dominik Wetzel",
	"Fabian Becker",
	"fengjiongmax",
	"Fredy Romero Sam",
	"Geequlim",
	"Gerrit Gro\303\237kopf",
	"Guldoman",
	"hatniX",
	"HeartBeast",
	"Heribert Hirth",
	"Hunter Jones",
	"Jonathon",
	"Josh 'Cheeseness' Bush",
	"JuDelCo",
	"Julian Murgia",
	"Juraj M\303\263za",
	"KC Chan",
	"Kevin Boyer",
	"Kevin Kamper Meejach Petersen",
	"Klavdij Voncina",
	"Kobi Malul",
	"Lisandro Lorea",
	"magodev",
	"Martin Nov\303\241k",
	"Matthew Fitzpatrick",
	"Matthew Valancy",
	"Matthias H\303\266lzl",
	"Max R.R. Collada",
	"Michael Gringauz",
	"Mikael Olsson",
	"MoM",
	"Moritz Laass",
	"nee",
	"Neil Blakey-Milner",
	"Nik Lee",
	"Niko Leopold",
	"nvgrod",
	"Pablo Seibelt",
	"Pan Ip",
	"Patrick Nafarrete",
	"Paul Mason",
	"Pawe\305\202 Kowal",
	"Pete Goodwin",
	"Pietro Vertechi",
	"rayos",
	"Richman Stewart",
	"Roger Smith",
	"Ryan Estes",
	"Sam Van Campenhout",
	"Sam Vila",
	"Sasori Olkof",
	"Scott D. Yelich",
	"Sootstone",
	"Tavo Tell",
	"TheHappieCat",
	"Theo Cranmore",
	"Tom Larrow",
	"Troy Bonneau",
	"UltyX",
	"Wout Standaert",
	"Xananax & karroffel",
	0
};
static const char *donor_bronze[] = {
	0
};
#endif
